AWSTemplateFormatVersion: 2010-09-09
Description: "Api gateway rewrite and redirect proof of concept (POC)."
Resources:
  ApiDefinition:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "RewriteRedirect"
      Description: "Rewrite redirect API to host many, many, rewrites and redirects!"
      FailOnWarnings: true
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
    - RewriteMethod1
    - RewriteMethod2
    Properties:
      RestApiId: !Ref ApiDefinition
      # Note: StageName is required by API Gateway. We recommend that you specify a name using any value
      # (see Examples) and that you don’t use this stage. We recommend not using this stage because it is tied to this
      # deployment, which means you can’t delete one without deleting the other. For example, if you delete this
      # deployment, API Gateway also deletes this stage, which you might want to keep. Instead, use the
      # AWS::ApiGateway::Stage resource to create and associate a stage with this deployment.
      StageName: TiedToStage
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref ApiDefinition
      StageName: prod
  RewriteResource1:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiDefinition
      ParentId: !GetAtt ApiDefinition.RootResourceId
      PathPart: "google"
  RewriteMethod1:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      Integration:
        Type: "HTTP"
        IntegrationHttpMethod: "GET"
        Uri: "https://www.google.com"
        IntegrationResponses:
        - StatusCode: 200
      ResourceId: !Ref RewriteResource1
      RestApiId: !Ref ApiDefinition
      MethodResponses:
      - StatusCode: 200
  RewriteResource2:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiDefinition
      ParentId: !Ref RewriteResource1 # under /google
      PathPart: "maps" # with ParentId, equates to /google/maps
  RewriteMethod2:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      Integration:
        Type: "HTTP"
        IntegrationHttpMethod: "GET"
        Uri: "https://www.google.com/maps"
        IntegrationResponses:
        - StatusCode: 200
      ResourceId: !Ref RewriteResource2
      RestApiId: !Ref ApiDefinition
      MethodResponses:
      - StatusCode: 200
  RewriteResource3:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiDefinition
      ParentId: !GetAtt ApiDefinition.RootResourceId # under /amazon
      PathPart: "amazon" # with ParentId, equates to /amazon
  RewriteMethod3:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      Integration:
        Type: "HTTP"
        IntegrationHttpMethod: "GET"
        Uri: "https://www.amazon.com"
        IntegrationResponses:
        - StatusCode: 200
      ResourceId: !Ref RewriteResource3
      RestApiId: !Ref ApiDefinition
      MethodResponses:
      - StatusCode: 200